name: Tag

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version Level'
        required: true
        default: 'minor'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Setup code
      uses: actions/checkout@v3

    - name: Setup Rust toolchain
      run: cargo install cargo-release

    - name: Dispatch Release
      run: |
        latest_version=$(gh release view --json tagName -q '.tagName')
        IFS="." read major minor patch <<<$( echo $latest_version)
        level="${{ github.event.inputs.level }}"
        case "$level" in
          "major" ) major=$(( major + 1)) ;;
          "minor" ) minor=$(( minor + 1)) ;;
          "patch" ) patch=$(( patch + 1)) ;;
        esac
        tag_name="${major}.${minor}.${patch}"
        cargo release ${tag_name} --tag-name ${tag_name} --execute --no-confirm -v
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
